{{ config(materialized='incremental') }}

select
    CLAIM_ID,
    PATIENT_ID,
    PROVIDER_ID,
    PRIMARY_PATIENT_INSURANCE_ID,
    SECONDARY_PATIENT_INSURANCE_ID,
    DEPARTMENT_ID,
    PATIENT_DEPARTMENT_ID,
    DIAGNOSIS_1,
    DIAGNOSIS_2,
    DIAGNOSIS_3,
    DIAGNOSIS_4,
    DIAGNOSIS_5,
    DIAGNOSIS_6,
    DIAGNOSIS_7,
    DIAGNOSIS_8,
    REFERRING_PROVIDER_ID,
    APPOINTMENT_ID,
    CURRENT_ILLNESS_DATE,
    SERVICE_DATE,
    SUPERVISING_PROVIDER_ID,
    STATUS_1,
    STATUS_2,
    STATUS_PATIENT,
    OUTSTANDING_1,
    OUTSTANDING_2,
    OUTSTANDING_PATIENT,
    LAST_BILLED_DATE_1,
    LAST_BILLED_DATE_2,
    LAST_BILLED_DATE_PATIENT,
    HEALTHCARE_CLAIM_TYPE_ID_1,
    HEALTHCARE_CLAIM_TYPE_ID_2
from {{ ref('stg_claims') }}

{% if is_incremental() %}
where CLAIM_ID not in (select CLAIM_ID from {{ this }})
{% endif %}